In [11]:
# 建立 list
a = [1, 3, 5, 7, 9]
print(a * 2)

b = [2, 4, 6, 8, 10]
print(a + b)

result = []
for i in range(len(a)):
    result.append(a[i] + b[i])
print(result)

print( [a[x] + b[x] for x in range(len(a))] )

[1, 3, 5, 7, 9, 1, 3, 5, 7, 9]
[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]
[3, 7, 11, 15, 19]
[3, 7, 11, 15, 19]


In [19]:
import numpy as np

# 透過 list 建立 ndarray
a = [1, 3, 5, 7, 9]
b = [2, 4, 6, 8, 10]

a_array = np.array(a)
b_array = np.array(b)

print(a_array)
print(a_array * 2)
print(a_array + b_array)


[1 3 5 7 9]
[ 2  6 10 14 18]
[ 3  7 11 15 19]


In [30]:
import random

print( [random.randint(50, 100) for x in range(5)] )

# 使用 numpy 建立 亂數
import numpy as np

np2_rand = np.random.randint(50, high=100, size=[3, 5])
print(np2_rand)

np2_rand[0] + np2_rand[1]


[63, 65, 85, 55, 53]
[[68 85 87 71 70]
 [57 86 97 56 75]
 [94 98 62 71 91]]


array([125, 171, 184, 127, 145])